import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

export default function Home() {
  const [dataSubmitted, setDataSubmitted] = useState([]);


  function handleUserSubmit(e){
    e.preventDefault();
    console.log("Form has been submitted");

    const dataObject = {
      location : e.target.location.value,
      min : e.target.min.value,
      max : e.target.max.value,
      avg : e.target.avg.value
    }

    setDataSubmitted([...dataSubmitted, dataObject]);

    console.log(dataSubmitted);
    console.log(dataObject);

  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between
        bg-green-400 p-4">
        <h1 className="text-3xl">
          Cookie Stand Admin
        </h1>
      </header>

      <main className="">
        <div className='bg-green-300 p-6 m-20'>
          <h1 className='flex justify-center p-4 text-xl'>
            Create Cookie Stand
          </h1>
          
          <form onSubmit={handleUserSubmit}>

            <div className='flex justify-center'>
              <label className='p-2'>location</label>
              <input className='pl-1' type="text"  name='location' placeholder='location'/>
            </div>

            <div className='flex justify-between'>
              <div className='m-4'>
                <label>Minimum Customers per Hour</label>
                <input type="text" name='min'/>
              </div>

              <div className='m-4'>
                <label>Maximum Customers per Hour</label>
                <input type="text" name='max'/>
              </div>

              <div className='m-4'>
                <label>Average Customers per Hour</label>
                <input type="text" name='avg'/>
              </div>

              <input className='p-5 py-1 bg-green-500' value="Create" type="submit"/>
            </div>
          </form>
        </div>

        <div className='flex justify-center p-4'>
          <p>Report table coming soon ...</p>
        </div>

        <div className='flex justify-center p-4'>
          <p>{JSON.stringify(dataSubmitted)}</p>
        </div>

      </main>

      <footer className="bg-green-400 p-4">
        <p> &#169;2021</p>
      </footer>
    </div>
  )
}
